---
- name: Install security packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fail2ban
  notify: restart services
- name: Enable automatic security updates
  apt:
    name: unattended-upgrades
    state: present
  notify: restart services
- name: Disable Password Authentication
#  TODO: Change to look for PasswordAuthentication set to yes on /ech/ssh/sshd_config.d/*.conf files
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PasswordAuthentication'
    line="PasswordAuthentication no"
    state=present
    backup=yes

- name: Disable Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin'
    line="PermitRootLogin no"
    state=present
    backup=yes
  notify:
    - restart ssh